### ISSUE TITLE
No ClassDeffFoundError. Selenium version 2.53.0

### ISSUE THREAD

**Issue by hemanthsridhar** [detro/ghostdriver#476]
java.lang.NoClassDefFoundError: org/openqa/selenium/browserlaunchers/Proxies
	at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:178)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
	at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:89)
	at org.etna.maincontroller.MainController.beforeTest(MainController.java:308)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.TestRunner.beforeRun(TestRunner.java:656)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.browserlaunchers.Proxies
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

**Comment by jerrywiltse** [comment]
I recall this issue.  It has repeatedly plagued me from time to time. I
don't have the silver bullet fix.

In one case, I thought I fixed it by switching the order that items were
added on the classpath, but you can't always control that.
I the latest case, I think i just upgraded to latest selenium, and used the
codeborne phantomjs library.
http://mvnrepository.com/artifact/com.codeborne/phantomjsdriver/1.2.1

Perhaps try the codeborne version instead.





Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by hemanthsridhar** [comment]
Thanks Jerry. It worked fine. Pretty slow though.

**Comment by jerrywiltse** [comment]
glad it worked. i don't notice if it's slow, but i don't have much to
compare to.

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by hemanthsridhar** [comment]
Ha ha. Alright. I had actually written a test suite and I had used only
phantomjs in my previous organisation. And boy oh boy wasn't that fast. I
see a little slowness. Anyways thanks once again. Take care.

**Comment by asolntsev** [comment]
@hemanthsridhar @jerrywiltse

Hi!
We have released an updated [phantomjsdriver version 1.3.0](http://search.maven.org/#artifactdetails%7Ccom.codeborne%7Cphantomjsdriver%7C1.3.0%7Cjar) that is compatible with latest selenium-java 2.53.0

**Comment by hemanthsridhar** [comment]
Fantastic
Will insert this dependency . Thank you so much :)

**Comment by hemanthsridhar** [comment]
Hi,

I executed around 20 simple test cases. Just navigating and verifying
breadcrumps and etc etc. There are few concerns which I am facing.
It is not supporting executeScript method of JavascriptExecutor class.
SOMETIMES the locator that I have given does not locate, even though in the
screenshot it is visible. Sometimes the locator does locate.
Getting a lot of StaleElementReferenceException which I am not getting in
other browsers.

Hope you guys can fix these issue.

Regards,

Hemanth Sridhar

**Comment by jerrywiltse** [comment]
Just to confirm, switching to the new phantomjsdriver 1.3.0 resolved your
noClassDefFound issue?

Gerald R. Wiltse
jerrywiltse@gmail.com

**Comment by hemanthsridhar** [comment]
Yep. Definitely. But the primary use of phantomJS is for faster execution
compared to other browsers. I actually noted down the time and it is taking
more time compared to chromedriver or firefoxdriver or even safari. Please
do fix this so that I can use it like I used to before :).

Regards,

Hemanth Sridhar

**Comment by asolntsev** [comment]
I guess it does not depend on phantomjsdriver, but rather phantomjs itself.
And definitely it depends on test.

Can you share some test that we can run to assure that phantomjsdriver is
really slower? It could help making it faster.

**Comment by hemanthsridhar** [comment]
I have written the test for my employer and I am supposed to disclose it.
(Hate this part though). I am really sorry but I cant share it. :(

Regards,

Hemanth Sridhar

**Comment by asolntsev** [comment]
Yes, sure.
But you can write analogous test using Google search or any other public
service.

Andrei Solntsev

2016-04-23 22:59 GMT+03:00 Hemanth Sridhar <notifications@github.com>:

**Comment by hemanthsridhar** [comment]
Hmmm.
 Well I am actually just hovering over a link and I am verifying the links
under that dropdown when I hover. Over there sometimes the links are not
showing up. And sometimes I get stale reference exception.

I am putting the breadcrumps navigation in a list and I am waiting for
explicit wait for *elements* since it is a List of breadcrumps. The wait
for the breadcrumps list is sometimes working and sometimes it is not.
Gives me no such element exception eventhough my screenshot shows that the
breadcrump is right there. I run the test again and it works fine.

I ran the hovering over the link and it worked faster in chrome and firefox
and it worked faster than in phantomjs.

PFA for two reports. One is PHANTOMJS. (named as ghost in the report
heading and the other is chrome). In phantomjs report you will find a
test TC_Brand_001_signedUser_hoverOverBrandsLinkInTopNavigationMenu
||  which is simply hovering over the brands link. If you click on it you
will get a dropdown which provides the screenshot and the log and the log
gives StaleElementReferenceException. *Make sure you unzip both the files*.
Also you will get the amount of time the suite took to execute. Chrome took
5 mins and phantom took 9 mins. You will see it in the report.

Hope this helps and I hope you will help me use PhantomJS again :D.

Regards,

Hemanth Sridhar

**Comment by hemanthsridhar** [comment]
And one more thing and this is weird.

 When I am running my code through a build management tool or testng or
junit or whatever,  I keep getting this line
phantomjs://platform/console++.js:263
in error but yet my test passes or fails.


Regards,

Hemanth Sridhar

**Comment by asolntsev** [comment]
It seems that all these problems are typical for any UI-tests, not only
PhantomJS.
Success or failure of tests depends on browser speed and other timing
issues.

Have you tried Selenide <http://selenide.org/>? It solves most of ajax,
hovering, timing issues out-of-the-box.

P.S. You forgot to attach some files?

Andrei Solntsev

2016-04-23 23:34 GMT+03:00 Hemanth Sridhar <notifications@github.com>:

**Comment by hemanthsridhar** [comment]
I meant i get that statement in the log irrespective of whether my tests
passes or fails. And no i didn't forget to attach any file. :)

Regards,

Hemanth Sridhar

**Comment by hemanthsridhar** [comment]
The reason why I asked you to look at that particular test case is for you
to screenshot. Nothing is loaded in that screenshot. My point is, in
chromedriver as well as firefox driver it is working perfectly fine. :).

Regards,

Hemanth Sridhar

**Comment by hemanthsridhar** [comment]
Issue still exists for the latest selenium jar. (3.0).

**Comment by prmichaelsen** [comment]
I've found placing selenium dependencies first in your pom.xml resolves this issue for me
