### ISSUE TITLE
ghostdriver release 1.3.0

### ISSUE THREAD

**Issue by jesg** [detro/ghostdriver#486]
@detro i'd like to help roll out ghostdriver 1.3.0 so we can include it in the phantomjs 2.5 release ariya/phantomjs#14458.

i plan on doing the following:
- [x] fix some of the unit tests
- [x] build atoms for selenium/webdriver 3.0.0
- [ ] run the selenium test suite and document the failures

thoughts?

**Comment by jesg** [comment]
the unit tests pass.

**Comment by henrik242** [comment]
+1

**Comment by solvingJ** [comment]
jesg, thanks for continuing to support this project. would be awesome!

**Comment by jesg** [comment]
@henrik242  @solvingJ the phantomjs issue is ariya/phantomjs#14553.  it is a general discussion about integrating ghostdriver changes upstream.

**Comment by davidmpaz** [comment]
Thanks for taking over!!

**Comment by anilreddy** [comment]
@jesg selenium 3.0 stable was released any plan integrating it?

**Comment by jesg** [comment]
@anilreddy yes i plan on building the selenium 3.0 atoms.

**Comment by eos1d3** [comment]
Any new progress?

**Comment by jesg** [comment]
@eos1d3 i've made a few pull requests to ghostdriver that fix various issues.  upstream phantomjs has stalled on providing an official way to build phantomjs for the 2.5 release.  hence i'm unable to test my changes on the next phantomjs release.

i can release an unofficial npm package for ghostdriver.  then you would be able to run an up to date version of ghostdriver.  the current version packaged in phantomjs is 2 years old.  would anyone be interested in this?  should this package track detro/ghostdriver's master branch or something else?

**Comment by eos1d3** [comment]
@jesg I will try if you release npm package.The current version is too old.

I am facing problems with Selenium HtmlunitDriver, and also HtmlUnit because of JavaScript engine bugs. Each has different problem.

I tested with GhosrDriver 1.2 and it looks good. I will do a more test soon. So if you have newer one, I will test it.

**Comment by jesg** [comment]
@eos1d3 do the following to run my most recent changes.

```sh
$ git clone https://github.com/jesg/ghostdriver ~/.ghostdriver
$ cd ~/.ghostdriver
$ PHANTOMJS_GHOSTDRIVER_PATH=`pwd`/src/main.js ./bin/ghostdriver --webdriver=8910
```

**Comment by eos1d3** [comment]
I use Java binding/Eclipse. And I use this maven with PhantomJS 2.1.1. Please tell me if this is correct as I did not run the above commands.

```
<dependency>
  <groupId>com.codeborne</groupId>
  <artifactId>phantomjsdriver</artifactId>
  <version>1.3.0</version>
</dependency>
```

With 1.2, there is starting error in log. And with 1.3, I got this and it looks good.
```

[INFO  - 2016-12-02T19:54:21.954Z] GhostDriver - Main - running on port 45562
[INFO  - 2016-12-02T19:54:22.019Z] Session [1e723fc0-b8c9-11e6-b28f-fb7357210485] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2016-12-02T19:54:22.019Z] Session [1e723fc0-b8c9-11e6-b28f-fb7357210485] - page.customHeaders:  - {}
[INFO  - 2016-12-02T19:54:22.019Z] Session [1e723fc0-b8c9-11e6-b28f-fb7357210485] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-12-02T19:54:22.019Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 1e723fc0-b8c9-11e6-b28f-fb7357210485

```


Basic operations like getting page, getting title, getting elements by ID/xpath all work.
And clicking and getingt text of element work well too.

But PhantonJS 2.1.1 has a problem (Not GhoshDriver) which does not existed in 1.9.8. It is when click a button, after JavaScript is executed.  A tag of `class="u_cbox_btn_recomm"` will be changed to  `class="u_cbox_btn_recomm u_cbox_btn_recomm_on"`. Only FireFoxDriver, HtmlUnit and PhantomJS 1.9.8 will show the updated class name. Selemium HtmlUnitDriver and PhantomJS still show the non-updated class name of `class="u_cbox_btn_recomm"`.

And another problem for PhantomJS again. Its element finding methods are much slower than any Webdriver and HtmlUnit. A lot of elements in a page takes ~10 seconds to locate. But PhantomJS takes 27 seconds. I do not know if it is my set up problem.

Do you have others tests for me to test?

**Comment by eos1d3** [comment]
I did not what I did before, or I changed my codes. Today I found the sendKeys never works.


```
[INFO  - 2016-12-03T23:05:30.490Z] GhostDriver - Main - running on port 20770
[INFO  - 2016-12-03T23:05:30.862Z] Session [fcd2b680-b9ac-11e6-a7de-c57543fe30a0] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":false,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2016-12-03T23:05:30.862Z] Session [fcd2b680-b9ac-11e6-a7de-c57543fe30a0] - page.customHeaders:  - {}
[INFO  - 2016-12-03T23:05:30.863Z] Session [fcd2b680-b9ac-11e6-a7de-c57543fe30a0] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.2.0","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-12-03T23:05:30.863Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: fcd2b680-b9ac-11e6-a7de-c57543fe30a0
[ERROR - 2016-12-03T23:05:32.289Z] RouterReqHand - _handle.error - {"line":264,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:264:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:120:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}

  phantomjs://platform/console++.js:263 in error
org.openqa.selenium.UnsupportedCommandException: TypeError - undefined is not a constructor (evaluating '_getTagName(currWindow).toLowerCase()')
Command duration or timeout: 13 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'MacPro', ip: '192.168.2.100', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.7.0_80'
Session ID: fcd2b680-b9ac-11e6-a7de-c57543fe30a0
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{platform=OS X 10.11, acceptSslCerts=false, javascriptEnabled=true, browserName=phantomjs, rotatable=false, driverVersion=1.2.0, locationContextEnabled=false, version=2.1.1, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=false, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, webStorageEnabled=false, driverName=ghostdriver, applicationCacheEnabled=false, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
	at Web.loadPage(Web.java:168)
	at TiamoGD.main(TiamoGD.java:199)
```

Line at `Web.loadPage(Web.java:168)` is pointed to `sendKeys` method.

I am still using 

```
<dependency>
  <groupId>com.codeborne</groupId>
  <artifactId>phantomjsdriver</artifactId>
  <version>1.3.0</version>
</dependency>
```

This is the code I start the driver

```
Logger.getLogger(PhantomJSDriverService.class.getName()).setLevel(Level.OFF);
DesiredCapabilities caps = new DesiredCapabilities();
String[] phantomArgs = new  String[] {
		"--load-images=false",
	};
caps.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, phantomArgs);
caps.setCapability(PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY, "phantomjs-2.1.1");    
driver = new PhantomJSDriver(caps);
driver.manage().timeouts().implicitlyWait(10, TimeUnit.MILLISECONDS);
driver.manage().timeouts().pageLoadTimeout(5000, TimeUnit.MILLISECONDS);

```

**Comment by jesg** [comment]
@eos1d3 your running version 1.3.0 of the ***java*** client to ghostdriver.  that does not package changes to ghostdriver.  you need to clone my repository and set `phantomjs.ghostdriver.path` to `src/main.js` in my repository.

```java
caps.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_PATH_PROPERTY, <absolute path to src/main.js>);
```

i would not set `--load-images=false`.

**Comment by eos1d3** [comment]
Cloned your repository. Added the following to start the webdriver:

```
DesiredCapabilities caps = new DesiredCapabilities();
String[] phantomArgs = new  String[] {
			};
caps.setCapability(PhantomJSDriverService.PHANTOMJS_CLI_ARGS, phantomArgs);
caps.setCapability(PhantomJSDriverService.PHANTOMJS_GHOSTDRIVER_PATH_PROPERTY, "/Volumes/Macintosh Data/Users/myname/Desktop/ghostdriver/src/main.js" );     
driver = new PhantomJSDriver(caps);
driver.manage().timeouts().implicitlyWait(10, TimeUnit.MILLISECONDS);
driver.manage().timeouts().pageLoadTimeout(5000, TimeUnit.MILLISECONDS);
```

Using 
```
<dependency>
  <groupId>com.codeborne</groupId>
  <artifactId>phantomjsdriver</artifactId>
  <version>1.3.0</version>
</dependency>
```

But still getting the exception as `sendKeys`. The log file is:
```
[INFO  - 2016-12-06T01:19:41.394Z] GhostDriver - Main - running on port 127.0.0.1:44020
[INFO  - 2016-12-06T01:19:41.705Z] Session [10533620-bb52-11e6-8512-b776173c8a7e] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":true,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2016-12-06T01:19:41.705Z] Session [10533620-bb52-11e6-8512-b776173c8a7e] - page.customHeaders:  - {}
[INFO  - 2016-12-06T01:19:41.705Z] Session [10533620-bb52-11e6-8512-b776173c8a7e] - page.zoomFactor:  - 1
[INFO  - 2016-12-06T01:19:41.705Z] Session [10533620-bb52-11e6-8512-b776173c8a7e] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.3.0-dev","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"},"webSecurityEnabled":true}
[INFO  - 2016-12-06T01:19:41.705Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: 10533620-bb52-11e6-8512-b776173c8a7e
[ERROR - 2016-12-06T01:19:43.216Z] RouterReqHand - _handle.error - {"line":266,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:266:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:121:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}
[ERROR - 2016-12-06T01:19:45.382Z] RouterReqHand - _handle.error - {"line":266,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:266:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:121:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}
[ERROR - 2016-12-06T01:19:47.543Z] RouterReqHand - _handle.error - {"line":266,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:266:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:121:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}
[ERROR - 2016-12-06T01:19:53.909Z] RouterReqHand - _handle.error - {"name":"Variable Resource Not Found","message":"{\"headers\":{\"Accept-Encoding\":\"gzip,deflate\",\"Connection\":\"Keep-Alive\",\"Content-Length\":\"89\",\"Content-Type\":\"application/json; charset=utf-8\",\"Host\":\"localhost:44020\",\"User-Agent\":\"Apache-HttpClient/4.5.1 (Java/1.8.0_77)\"},\"httpVersion\":\"1.1\",\"method\":\"POST\",\"post\":\"{\\\"id\\\":\\\":wdc:1480987191599\\\",\\\"using\\\":\\\"xpath\\\",\\\"value\\\":\\\".//em[@class='u_cbox_cnt_unrecomm']\\\"}\",\"url\":\"/session/10533620-bb52-11e6-8512-b776173c8a7e/element/:wdc:1480987191599/elements\",\"urlParsed\":{\"anchor\":\"\",\"query\":\"\",\"file\":\"elements\",\"directory\":\"/session/10533620-bb52-11e6-8512-b776173c8a7e/element/:wdc:1480987191599/\",\"path\":\"/session/10533620-bb52-11e6-8512-b776173c8a7e/element/:wdc:1480987191599/elements\",\"relative\":\"/session/10533620-bb52-11e6-8512-b776173c8a7e/element/:wdc:1480987191599/elements\",\"port\":\"\",\"host\":\"\",\"password\":\"\",\"user\":\"\",\"userInfo\":\"\",\"authority\":\"\",\"protocol\":\"\",\"source\":\"/session/10533620-bb52-11e6-8512-b776173c8a7e/element/:wdc:1480987191599/elements\",\"queryKey\":{},\"chunks\":[\"session\",\"10533620-bb52-11e6-8512-b776173c8a7e\",\"element\",\":wdc:1480987191599\",\"elements\"]}}","line":80,"sourceURL":"phantomjs://code/router_request_handler.js","stack":"_handle@phantomjs://code/router_request_handler.js:80:82"}
[INFO  - 2016-12-06T01:19:53.922Z] ShutdownReqHand - _handle - About to shutdown

```

The error messages from console are list below, while  `Web.loadPage(Web.java:165)` is pointed to sendKeys method call.

 ```
[ERROR - 2016-12-06T01:19:43.216Z] RouterReqHand - _handle.error - {"line":266,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:266:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:121:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}

  phantomjs://platform/console++.js:263 in error
org.openqa.selenium.UnsupportedCommandException: TypeError - undefined is not a constructor (evaluating '_getTagName(currWindow).toLowerCase()')
Command duration or timeout: 18 milliseconds
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'MacPro', ip: '192.168.2.100', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.1.1, platform=OS X 10.11, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.3.0-dev, webSecurityEnabled=true, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 10533620-bb52-11e6-8512-b776173c8a7e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:327)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:122)
	at Web.loadPage(Web.java:165)
```

**Comment by jesg** [comment]
@eos1d3 here is my wild guess at what is going on

```html
<div class="first_class second third"></div>
```

in this case `.//div[@class="third"]` does not match the element.  it should be `.//div[contains(@class, "third")]`.  or you can use a css selector `div.third`.

i would expect an error to be thrown in your client code when ghostdriver fails to find the element.  i might be missing something.  do you have an example i can use to reproduce this error?

**Comment by eos1d3** [comment]
@jesg I believe you are talking the problem of `class="u_cbox_btn_recomm"` and its change to `class="u_cbox_btn_recomm u_cbox_btn_recomm_on"` after clicking a button and  Javascript is executed.

I understand your point. But it is not the case. Selenium HtmlUnitDriver just do not update the class.
Before clicking the button, the element has be located and save in a variable. After clicking the button, I use `getAttribute("class")` to get the class and it is not updated. But with the same code, FireFoxDriver and HtmlUnit can return class attribute of `u_cbox_btn_recomm u_cbox_btn_recomm_on`.

I still need to re-confirm if PhantomJS 2.1.1 has this problem. But before this, I need the `sendKeys` to work first. My `sendKeys` problem is similar to this:  https://github.com/ariya/phantomjs/issues/10993

**Comment by jesg** [comment]
@eos1d3 can you provide some html/javascript that triggers this issue?

**Comment by eos1d3** [comment]
@jesg Please try this. It can test both the old version and new version. https://github.com/eos1d3/GhostDriverTest

**Comment by jesg** [comment]
@eos1d3 the following error is thrown in `_getTagName`.   looks like twitter disables javascript eval.  setting `--web-security=false` did not fix the problem for me.

```json
{"status":13,"value":{"message":"Refused to evaluate a string     as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src https://abs.twimg.com https://abs-0.twimg.com https://twitter.com https://mobile.twitter.com\".\n"    }}
```

**Comment by eos1d3** [comment]
Hi @jesg , 

There are two tests in main. `test198` is for PhantomJS 1.9.8. it runs without any error.
This is its console output:
```
Dec 07, 2016 9:35:03 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /Volumes/Macintosh Data/Users/andy/Documents/workspace/GhostDriverTest/phantomjs-1.9.8
Dec 07, 2016 9:35:03 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 28805
Dec 07, 2016 9:35:03 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--load-images=false, --webdriver=28805, --webdriver-logfile=/Volumes/Macintosh Data/Users/andy/Documents/workspace/GhostDriverTest/phantomjsdriver.log]
Dec 07, 2016 9:35:03 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
PhantomJS is launching GhostDriver...
[INFO  - 2016-12-07T13:35:04.861Z] GhostDriver - Main - running on port 28805
[INFO  - 2016-12-07T13:35:05.117Z] Session [f657c890-bc81-11e6-ba6d-9911fc05b235] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":false,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/534.34 (KHTML, like Gecko) PhantomJS/1.9.8 Safari/534.34","webSecurityEnabled":true}
[INFO  - 2016-12-07T13:35:05.118Z] Session [f657c890-bc81-11e6-ba6d-9911fc05b235] - page.customHeaders:  - {}
[INFO  - 2016-12-07T13:35:05.118Z] Session [f657c890-bc81-11e6-ba6d-9911fc05b235] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"1.9.8","driverName":"ghostdriver","driverVersion":"1.1.0","platform":"mac-unknown-32bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"}}
[INFO  - 2016-12-07T13:35:05.118Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: f657c890-bc81-11e6-ba6d-9911fc05b235
Login
Name:
Password
Click
Cookies: npic,LnTI0BIdslNF7NrZCvF     ..... vmLfFiG/dwCA==
URL: http://entertain.naver.com/read?oid=213&aid=0000929636
Done

```

And `test211` is for PhantomJS test. It has exception at sendKeys (at `WebDriverTest.test211(WebDriverTest.java:34)`)

The console output is:
```
Dec 07, 2016 9:40:44 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /Volumes/Macintosh Data/Users/andy/Documents/workspace/GhostDriverTest/phantomjs
Dec 07, 2016 9:40:44 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 39525
Dec 07, 2016 9:40:44 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--load-images=false, /Volumes/Macintosh Data/Users/andy/Desktop/ghostdriver-master/src/main.js, --port=39525, --logFile=/Volumes/Macintosh Data/Users/andy/Documents/workspace/GhostDriverTest/phantomjsdriver.log]
Dec 07, 2016 9:40:44 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
[INFO  - 2016-12-07T13:40:45.462Z] GhostDriver - Main - running on port 127.0.0.1:39525
[INFO  - 2016-12-07T13:40:45.817Z] Session [c16a0520-bc82-11e6-8ff6-4bb424004f93] - page.settings - {"XSSAuditingEnabled":false,"javascriptCanCloseWindows":true,"javascriptCanOpenWindows":true,"javascriptEnabled":true,"loadImages":false,"localToRemoteUrlAccessEnabled":false,"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/538.1 (KHTML, like Gecko) PhantomJS/2.1.1 Safari/538.1","webSecurityEnabled":true}
[INFO  - 2016-12-07T13:40:45.817Z] Session [c16a0520-bc82-11e6-8ff6-4bb424004f93] - page.customHeaders:  - {}
[INFO  - 2016-12-07T13:40:45.817Z] Session [c16a0520-bc82-11e6-8ff6-4bb424004f93] - page.zoomFactor:  - 1
[INFO  - 2016-12-07T13:40:45.817Z] Session [c16a0520-bc82-11e6-8ff6-4bb424004f93] - Session.negotiatedCapabilities - {"browserName":"phantomjs","version":"2.1.1","driverName":"ghostdriver","driverVersion":"1.3.0-dev","platform":"mac-10.11 (El Capitan)-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"proxyType":"direct"},"webSecurityEnabled":true}
[INFO  - 2016-12-07T13:40:45.817Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: c16a0520-bc82-11e6-8ff6-4bb424004f93
Login
Name:
[ERROR - 2016-12-07T13:40:47.229Z] RouterReqHand - _handle.error - {"line":266,"sourceURL":"phantomjs://code/webelement_request_handler.js","stack":"_postValueCommand@phantomjs://code/webelement_request_handler.js:266:52\n_handle@phantomjs://code/webelement_request_handler.js:72:30\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/session_request_handler.js:121:42\n_reroute@phantomjs://code/request_handler.js:61:20\n_handle@phantomjs://code/router_request_handler.js:78:46"}

  phantomjs://platform/console++.js:263 in error
org.openqa.selenium.UnsupportedCommandException: TypeError - undefined is not a constructor (evaluating '_getTagName(currWindow).toLowerCase()')
Command duration or timeout: 12 milliseconds
Build info: version: '2.41.0', revision: '3192d8a6c4449dc285928ba024779344f5423c58', time: '2014-03-27 11:29:39'
System info: host: 'MacPro', ip: '192.168.2.100', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.11.6', java.version: '1.8.0_77'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=2.1.1, platform=MAC, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.3.0-dev, webSecurityEnabled=true, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: c16a0520-bc82-11e6-8ff6-4bb424004f93
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:193)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:145)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:595)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:89)
	at WebDriverTest.test211(WebDriverTest.java:34)
	at WebDriverTest.main(WebDriverTest.java:94)
Done



```

You better to define your own `twitterName` and `twitterPassword`. But it is not important as the test is to show sendKeys functionality.

**Comment by jesg** [comment]
@eos1d3 the root cause is not being able to evaluate javascript on [line 522](https://github.com/jesg/ghostdriver/blob/master/src/request_handlers/webelement_request_handler.js#L522).  i think we may be able to work around this by creating custom atoms for ghostdriver.

**Comment by jesg** [comment]
the initial (unofficial) npm package is complete https://www.npmjs.com/package/ghostdriver.

run the following to install **with** the `phantomjs-prebuilt` package.
```
npm install --global ghostdriver
```
run the following to install **without** the `phantomjs-prebuilt` package.
```
npm install --global --no-optional ghostdriver
```

**Comment by jesg** [comment]
the java build is janky so i created #504.  the current build has a cyclic dependency which is annoying for end users.

**Comment by jesg** [comment]
@eos1d3 the issue you where having with pages that have a content security policy should now be fixed on my master branch.  in other words you should be able to send keys and click on elements that are on the twitter login page.

**Comment by eos1d3** [comment]
Will try again later next week. Thanks!

**Comment by eos1d3** [comment]
Hi, is there any binary or maven to test the new version?

**Comment by jesg** [comment]
> Hi, is there any binary or maven to test the new version?

ghostdriver has not been included in the phantomjs binary release yet.  you can use the [npm package](https://www.npmjs.com/package/ghostdriver).  i've not included my fix for page loading yet so you will run into a lot of problems when running it on phantomjs 2.5.0-beta.

you can use the following to get the java client.
```
<dependency>
    <groupId>com.codeborne</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>1.4.0</version>
</dependency>
```

or

```
<dependency>
    <groupId>com.github.jesg</groupId>
    <artifactId>phantomjsdriver</artifactId>
    <version>3.0.0-beta1</version>
</dependency>
```

the version i built does not have a cyclic dependency on `org.seleniumhq.selenium:selenium-java`.

**Comment by detro** [comment]
Just wanted to leave a note here too: @jesg submitted an amazing PR that I have just [finished reviewing](https://github.com/detro/ghostdriver/pull/511#pullrequestreview-23956048) and I'm confident we are now really close to a new substantial release.

Also, @jesg will be soon added to the list of the official maintainers.

**Comment by eos1d3** [comment]
This will be great.

And is there a chance to have GhostDriver included in latest PhantomJS?

**Comment by jesg** [comment]
>  And is there a chance to have GhostDriver included in latest PhantomJS?

that is the plan.  see ariya/phantomjs#14553
