### ISSUE TITLE
Python + Selenium + PhantomJS fails in 32 bits

### ISSUE THREAD

**Issue by dbareiro** [detro/ghostdriver#494]
Hi all,

I am developing a script/plugin for Nagios using Python with Selenium and PhantomJS. The environment used for develop was:

- Debian GNU/Linux Jessie 64 bits.
- Selenium installed via `pip`: `pip install selenium`.
- PhantomJS downloaded from here: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2.

The script/plugin worked flawlessly on 64-bit, but it failed on 32-bit.

Testing on 64 bits:

```
$ python check_hsb_adsl_uptime.py 1.2.3.4 password
OK: ADSL Uptime: 16:04:22, Downstream rate: 2016 kbps, Upstream rate: 608 kbps
```

Testing on 32 bits:

```
# python check_hsb_adsl_uptime.py 1.2.3.4 password
Traceback (most recent call last):
  File "check_hsb_adsl_uptime.py", line 86, in <module>
    sbtn = driver.find_element_by_xpath('html/body/table[2]/tbody/tr[2]/td/center/input[2]')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: {"errorMessage":"Unable to find element with xpath 'html/body/table[2]/tbody/tr[2]/td/center/input[2]'","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"133","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:43963","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"using\": \"xpath\", \"sessionId\": \"8b6ea550-af69-11e6-bce3-7d03aff5ea6d\", \"value\": \"html/body/table[2]/tbody/tr[2]/td/center/input[2]\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/8b6ea550-af69-11e6-bce3-7d03aff5ea6d/element"}}
Screenshot: available via screen
```

The 32 bits environment used was:

- Debian GNU/Linux Jessie 32 bits.
- Selenium installed via `pip`: `pip install selenium`.
- PhantomJS downloaded from here: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-i686.tar.bz2

I also attached the `ghostdriver.log` file for if there is information here that could be useful.

[ghostdriver.log.txt](https://github.com/detro/ghostdriver/files/602353/ghostdriver.log.txt)

Thanks in advance.

Kind rregards,
Daniel

**Comment by jesg** [comment]
phantomjs project is dropping support for 32bit linux.

**Comment by dbareiro** [comment]
Hi, jseg.

Thanks for your reply. Unfortunately I no longer have the device with which I was programming the Nagios plugin I mentioned, so I did not continue testing. However I have used Python + Selenium + PhantomJS in a 32 bit environment creating other Nagios plugins for other devices and they worked without problems.

So I'm not sure what the problem might have been. Let's close the ticket for now, please. Unless you want to add something else (I noticed you closed the ticket and then reopened it).

Kind regards,
Daniel

**Comment by jesg** [comment]
> So you think 32-bit support will not be available in the future?

i'm not sure.  the 2.5 beta release did not have a 32bit linux build but ticket [14459](https://github.com/ariya/phantomjs/issues/14459) specifies a 32bit linux build.

there are a lot of complaints about xpath so i'll smoke test it.
