### ISSUE TITLE
URLError - urlopen Connection Refused

### ISSUE THREAD

**Issue by daredevil82** [detro/ghostdriver#521]
## Meta -
OS:  Ubuntu 14.04
Selenium Version:  2.53.2
Browser:  PhantomJS 2.1.1

## Actual Behavior - URLError 111 - Connection Refused
```
[2017-03-30 14:14:41,399: ERROR/Worker-3] Two attempts failed for url [http://s3-us-west-2.amazonaws.com/degreedata-html/9240/buweb.binghamton.edu/bulletin/program4a20.html]
Traceback (most recent call last):
  File "qualitycontrol/tasks/screenshot.py", line 132, in _screenshot
    self._driver.get(url)
  File "/home/ubuntu/.virtualenvs/degreedata2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 245, in get
    self.execute(Command.GET, {'url': url})
  File "/home/ubuntu/.virtualenvs/degreedata2.7/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 231, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/home/ubuntu/.virtualenvs/degreedata2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 395, in execute
    return self._request(command_info[0], url, body=data)
  File "/home/ubuntu/.virtualenvs/degreedata2.7/lib/python2.7/site-packages/selenium/webdriver/remote/remote_connection.py", line 463, in _request
    resp = opener.open(request, timeout=self._timeout)
  File "/usr/local/lib/python2.7.11/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7.11/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7.11/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7.11/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7.11/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 111] Connection refused>
```

I have two Celery tasks running in sequence.  The first scrapes and mirrors a website at a specific URL and uploads to a S3 bucket with a db ID as the folder prefix.  Upon upload completion, the second task executes via retrieving a set number of keys from the uploaded prefix and executing a screenshot using PhantomJS.  These tasks execute sequentially, with a 90 second delay between the two.

With a large number of websites, I've been getting the above stacktrace when attempting screenshots, despite the ability to load the URL in the browser without a problem.

I configure Phantom in the task via

```	
self._phantom_path = os.path.join(LOGGING_FILE, 'phantom.log')
self._phantom_settings = {
        'phantomjs.page.settings.loadImages': True,
        'phantomjs.page.settings.userAgent':  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, '
                                              'like Gecko) Chrome/49.0.2623.87 Safari/537.36'
    }

    cookies_file = os.path.join(os.path.expanduser('~'), 'phantom-cookies.txt')
    self._driver = PhantomJS(PHANTOMJS_PATH,
                            service_log_path = self._phantom_path,
                            desired_capabilities = self._phantom_settings,
                            service_args = ['--debug=true',
                                            '--webdriver-loglevel=DEBUG',
                                            '--cookies-file={}'.format(cookies_file)])

    self._driver.implicitly_wait(15)
    self._driver.set_page_load_timeout(15)
    self._driver.maximize_window()
```
and call it with the following method:

```
    def _screenshot(self, url, retry = False):
        try:
            self._driver.get(url)
            return self._driver.get_screenshot_as_png()

        except TimeoutException as e:
            self.logger.error('Timeout exception for URL [{}].  Message [{}]'.format(url, e), exc_info = True)
            if not retry:
                self.logger.info('Retrying screenshot for url [{}]'.format(url))
                self._screenshot(url, True)
            else:
                self.logger.error('Two attempts failed for url [{}]'.format(url), exc_info = True)
                return None
        except URLError as e:
            self.logger.error("URLError for url [{}]. [{}]".format(url, e), exc_info = True)
            if not retry:
                self.logger.info('Retrying screenshot for url [{}]'.format(url))
                self._screenshot(url, True)
            else:
                self.logger.error('Two attempts failed for url [{}]'.format(url), exc_info = True)
                return None    
```

In my case, I always get the `URLError` in the logs, with the stack trace displayed above.

I'm pretty stumped here.  Are there any suggestions?

**Comment by jesg** [comment]
@daredevil82 thanks for the detailed information. 👍 

> Are there any suggestions?

you may want to look at #334 .  in paticular look at  nkovacs's analysis.

you can try running on ghostdriver 2.0.0.  ghostdriver 2.0.0 does not fix the issue nkovacs pointed out when running on phantomjs 2.1.1.

**Comment by daredevil82** [comment]
@jesg thanks for the response.  Seems as if you expect the behavior reported to be fixed with v2.5.  Is there a location where I could get the source for the beta and test with my use case?

**Comment by jesg** [comment]
> Seems as if you expect the behavior reported to be fixed with v2.5.

correct.

> Is there a location where I could get the source for the beta and test with my use case?

you can build phantomjs from source but imo it is a pia.  it can easily suck up 2-3 days to figure out how to do it correctly.  the binaries for 2.5 are [here](https://bitbucket.org/ariya/phantomjs/downloads/).  2.5 beta is not built with ghostdriver 2.0.0.  you will need to install some shared libraries.

ghostdriver is available on [npm](https://www.npmjs.com/package/ghostdriver).  you will need to set the `PHANTOMJS_BINARY_PATH` environment variable to the 2.5 beta binary.

if you do not like npm then you can clone the ghostdriver repository and run the [bash script](https://github.com/detro/ghostdriver/blob/master/bin/ghostdriver.sh).  you will need to set `PHANTOMJS_GHOSTDRIVER_PATH` to `src/main.js` and `PHANTOMJS_PATH` to the phantomjs binary.  (looks like the environment variable names are  inconsistent... that needs to be fixed).
