### ISSUE TITLE
Headless driver showing "NoSuchMethodError" for both htmlunit and phantom js

### ISSUE THREAD

**Issue by nagarjun64** [detro/ghostdriver#539]
**OS:**  
OSX

**Selenium Version:**  
3.4.0

**Browser:**  
headless HTML unit driver (2.24), phantom js driver (2.1)

## Expected Behavior -

Tests are supposed to execute in headless configuration mode with out any issues

## Actual Behavior -

Getting the error
```
java.lang.NoSuchMethodError: com.gargoylesoftware.htmlunit.html.HtmlInput.setValueAttribute(Ljava/lang/String;)Lcom/gargoylesoftware/htmlunit/Page;
	at org.openqa.selenium.htmlunit.HtmlUnitWebElement.clear(HtmlUnitWebElement.java:247)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy19.clear(Unknown Source)

```
## Steps to reproduce -

1. Download the project [](https://drive.google.com/open?id=0B4SgyzyvwKhicFAwSVhIT3B3Qzg)
2. Run the pom file (browser config reader maintained in ReadPropertiesFile.java)
3. Notice that above exception occurs

**Comment by jesg** [comment]
@nagarjun64 can you try version 1.4.3?

**Comment by nagarjun64** [comment]
@jesg phantomjs 1.4.3?

**Comment by jesg** [comment]
@nagarjun64 

> phantomjs 1.4.3?

no the java client in the pom.xml.
