### ISSUE TITLE
Unable  to  execute selenium  test case in phantom Js  in  Jboss server  from linux  OS 

### ISSUE THREAD

**Issue by Soumya4** [detro/ghostdriver#542]
Hi ,

I am trying to  execute selenium  test  case using phantom JS  from linux machine. The driver is able to  initialize the phantom JS  driver but  after  that  url  is not able to  hit.
The configuration  which  I am currently having in linux :   phantomjs-2.1.1-linux-x86_64
The selenium driver jar  version is  selenium 2.53  and phantom js driver version  is 1.2.1
Please suggest  me  is there any  version mismatching issue or it is due to  other issue.
A quick  response is highly appreciable.

Regards,
Soumya

**Comment by jesg** [comment]
you may want to analyze your dependencies to check if you have cyclic a dependency.  which you might because that jar is probably not built properly.

the project supports selenium greater than 3.1.0.

**Comment by Soumya4** [comment]
If I will use phantom JS 1.8  will be it be OK  with  selenium 2.53.

**Comment by Soumya4** [comment]
The phantomjs code is working in  Windows machine but only in linux I am getting issue while running phantom Js after  driver initialization .
org.openqa.selenium.UnsupportedCommandException: Variable Resource Not Found - {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Host":"localhost:30638","User-Agent":"Apache-HttpClient/4.3.1 (java 1.5)"},"httpVersion":"1.1","method":"DELETE","url":"/session/901e53f0-4d18-11e7-b03e-ab065dde70e8","urlParsed":{"anchor":"","query":"","file":"901e53f0-4d18-11e7-b03e-ab065dde70e8","directory":"/session/","path":"/session/901e53f0-4d18-11e7-b03e-ab065dde70e8","relative":"/session/901e53f0-4d18-11e7-b03e-ab065dde70e8","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/session/901e53f0-4d18-11e7-b03e-ab065dde70e8","queryKey":{},"chunks":["session","901e53f0-4d18-11e7-b03e-ab065dde70e8"]}} Command duration or timeout: 52 milliseconds Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46' System info: host: 'ION-MUM-PreQA-JB-61-75', ip: '10.10.61.75', os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.32-696.el6.x86_64', java.version: '1.7.0_79' Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver Capabilities [{platform=LINUX, acceptSslCerts=false, javascriptEnabled=true, browserName=phantomjs, rotatable=false, driverVersion=1.2.0, locationContextEnabled=false, version=2.1.1, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=false, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, webStorageEnabled=false, driverName=ghostdriver, applicationCacheEnabled=false, takesScreenshot=true}] at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:701) at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:526) at com.tcsion.base.DemoBaseClass.ShutDown(DemoBaseClass.java:75) at com.tcsion.main.DemoMainProject.executeAutomationBotSuite(DemoMainProject.java:58) at com.tcs.botframework.thread.BotFrameworkMainThread.executeSchedular(BotFrameworkMainThread.java:82) at com.tcs.botframework.thread.BotFrameworkMainThread.run(BotFrameworkMainThread.java:33) at java.lang.Thread.run(Thread.java:745) ... Removed 19 stack frames

**Comment by jesg** [comment]
@Soumya4 do you have the ghostdriver debug logs?  also are you running phantomjs directly or indirectly through selenium grid.

**Comment by Soumya4** [comment]
I am running phantomJs directly not using selenium grid.ghostdriver debug log I am not able to get .the phantomjsdriver.log file is not generating ..

**Comment by jesg** [comment]
@Soumya4 are you able to provide a small reproducible example?  i'm having a hard time guessing what is going wrong at this point.
