### ISSUE TITLE
How can I resolve the PhantomJSDriver() from a different jar with same structure like selenium

### ISSUE THREAD

**Issue by Debanjan-B** [detro/ghostdriver#560]
How can I resolve the PhantomJSDriver() from a different jar with same structure like selenium?

Till a few days back PhantomJSDriver was released bundled along with selenium-server-standalone-v.v.v.jar. So my Class was working fine as :

```
import java.io.File;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.phantomjs.PhantomJSDriver;

public class A_PhantomJS
{
    public static void main(String[] args) 
    {
          File path=new File("C:\\Utility\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe");
          System.setProperty("phantomjs.binary.path",path.getAbsolutePath());
          WebDriver driver= new PhantomJSDriver();
          driver.manage().window().maximize();
          driver.get("https://www.google.co.in");
    }
}
```

Now selenium-server-standalone-v.v.v.jar doesn't bundles the jar for PhantomJSDriverdependency.

So I have downloaded the jar phantomjsdriver-1.1.0.jar and added as an external jar to my project.

You can see the structure of the phantomjsdriver-1.1.0.jar is similar to what it was earlier when it was bundled with selenium-server-standalone-v.v.v.jar

![phantomjsdriver](https://user-images.githubusercontent.com/26503213/34827365-f0bbc97c-f6ff-11e7-9282-26a9f4310487.png)

Now, though my Class gets resolved through :

import org.openqa.selenium.phantomjs.PhantomJSDriver;
But I am facing a Runtime exception of java.lang.NoClassDefFoundError exception caused by java.lang.ClassNotFoundException as follows :

```
Exception in thread "main" java.lang.NoClassDefFoundError: org/openqa/selenium/browserlaunchers/Proxies
    at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:178)
    at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
    at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:89)
    at demo.A_PhantomJS.main(A_PhantomJS.java:15)
Caused by: java.lang.ClassNotFoundException: org.openqa.selenium.browserlaunchers.Proxies
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 4 more
```

Line 15 being :

WebDriver driver= new PhantomJSDriver();
As per the error I have searched for org.openqa.selenium.browserlaunchers.Proxies within the phantomjsdriver-1.1.0.jar unable to find any clue.

![noclassdeffounderror](https://user-images.githubusercontent.com/26503213/34827419-1dd07926-f700-11e7-8553-fade53a23cb8.png)

**Comment by Debanjan-B** [comment]
Thanks Everyone.

The Question is solved now through Simon's comment in another user group : **`There's a version of phantomjsdriver ('com.codeborne:phantomjsdriver:jar:1.4.4') that appears to be kept up to date with latest selenium releases. I'd suggest using that.`**
